### ISSUE TITLE
[FEATURE] Allow opening .csv and .xlsx files as spreadsheets

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-editor#38]
These files are used frequently in different kinds of analyses and configuration and may be more frequently edited than most configuration files. There are node packages to read excel files.

A few candidates:
- [Handsontable](https://handsontable.com/) -- commercial, non-permissive license
- [Ag-grid](https://www.ag-grid.com/) -- MIT license but may paywall best features in commercial license
- [ReactDataGrid](https://reactdatagrid.io/) -- MIT license but may paywall best features in commercial license
- [ReactGrid](https://reactgrid.com/)  -- MIT license but appears inactive

There might be other, better options, but this seems to be a very commercialized product space.

**Comment by rubenthoms** [comment]
Implemented by #82.
